### ISSUE TITLE
Can't run WDIO tests inside container with volume mounts

### ISSUE THREAD

**Issue by mattschutt** [cerner/terra-toolkit#339]
# Bug Report
As we're having more developers that have to utilize Windows devices for their work, we're trying to push development to happen inside the containers so we can work cross-system.  Currently, a docker-compose volume cannot be utilized for the errorScreenshots directory. 

## Description
A docker-compose service like this will succeed, but the error evidence is left inside the container:

```
  wdio:
    command: bash -c "npm run test:wdio:local"
    image: ${IMAGE}:${TAG}
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./package.json:/app/package.json
      - ./wdio.conf.js:/app/wdio.conf.js
```

In it's current location, in order to volume mount it into the container, the service would need to be:

```
  wdio:
    command: bash -c "npm run test:wdio:local"
    image: ${IMAGE}:${TAG}
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./package.json:/app/package.json
      - ./wdio.conf.js:/app/wdio.conf.js
      - ./errorScreenshots:/app/errorScreenshots/
```

However, this results in the following error:

```
docker-compose up wdio
..,.
wdio_1         | /app/node_modules/terra-toolkit/node_modules/fs-extra/lib/remove/rimraf.js:262
wdio_1         |       throw er
wdio_1         |       ^
wdio_1         | 
wdio_1         | Error: EBUSY: resource busy or locked, rmdir '/app/errorScreenshots'
wdio_1         |     at Object.fs.rmdirSync (fs.js:846:18)
wdio_1         |     at rmdirSync (/app/node_modules/terra-toolkit/node_modules/fs-extra/lib/remove/rimraf.js:276:13)
wdio_1         |     at Object.rimrafSync [as removeSync] (/app/node_modules/terra-toolkit/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
wdio_1         |     at screenshotDirectories.forEach (/app/node_modules/terra-toolkit/scripts/wdio/clean-screenshots.js:33:10)
wdio_1         |     at Array.forEach (<anonymous>)
wdio_1         |     at cleanSnapshots (/app/node_modules/terra-toolkit/scripts/wdio/clean-screenshots.js:30:25)
wdio_1         |     at Object.<anonymous> (/app/node_modules/terra-toolkit/scripts/wdio/wdio-runner-cli.js:47:1)
wdio_1         |     at Module._compile (module.js:635:30)
wdio_1         |     at Object.Module._extensions..js (module.js:646:10)
wdio_1         |     at Module.load (module.js:554:32)
wdio_1         | npm ERR! code ELIFECYCLE
wdio_1         | npm ERR! errno 1
wdio_1         | npm ERR! Exit status 1
wdio_1         | npm ERR! 
wdio_1         | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
wdio_1 exited with code 1
```

## Steps to Reproduce
Utilize the services defined above in a docker-compose file for a generated component to run into the issue.

## Expected Behavior
Tests should execute from within a container.  I'm guessing development has mainly been done locally on devices which is why this hasn't been an issue.  As we move forward that should probably not be a safe assumption.

## Possible Solution
I think there are 2 possible remedies:
1) Rather than putting it in the root directory, put it in the tests directory.
2) Rather than deleting it with ['fs.removesync'](https://github.com/cerner/terra-toolkit/blob/master/scripts/wdio/clean-screenshots.js#L33) it could utilize ['fs.emptyDirSync'](https://github.com/jprichardson/node-fs-extra/blob/master/docs/emptyDir-sync.md)

Perhaps both would be the best solution.  Utilizing the gitignore file prevents it from getting checked in, and we can now successfully run these within the container across systems.

## Environment
Reproduced on both Windows and OS X

https://github.cerner.com/scheduling/manual-scheduling-js/blob/wdio-tests/docker-compose.yml#L58

## @ Mentions
@ryanthemanuel
