### ISSUE TITLE
Possible docker error in travis builds after upgrading from 1.x to 5.x

### ISSUE THREAD

**Issue by jasonkshar** [cerner/terra-toolkit#350]
# Issue Description

Uplifted from v1.2.2 to v5.12.0 and went through all the upgrade/migration guides. But now my Travis builds fail when trying to run the wdio tests with:
```
ERROR: getaddrinfo ENOTFOUND standalone-chrome standalone-chrome:4444
```

## Additional Context / Screenshots

Everything builds and tests pass as they have prior to uplift. The nightwatch tests were removed and rewritten to use wdio. The docker tests run locally, but seem to fail on travis. 

I'm wondering, is there some additional configuration I need to apply to my travis builds? My `.travis.yml` is pretty small:
```
language: node_js
sudo: required
jdk: oraclejdk8
branches:
  only:
    - master
node_js:
  - '9'
  - '9.11'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
  - npm run test:wdio
```
and the `test:wdio` is pretty simple: `"test:wdio": "wdio tests/wdio.conf.js"`. The wdio configuration is also pretty small:
```
const wdioConfig = require('terra-toolkit/config/wdio/wdio.conf');
const webpackConfig = require('./features/config.js');
const path = require('path');

const config = {
  ...wdioConfig.config,
  webpackConfig,
  specs: [path.join('tests', 'wdio', '*.js')],
};

if (config.seleniumDocker) {
  config.seleniumDocker.cleanup = true;
}

exports.config = config;
```

Any help would be appreciated.
