### ISSUE TITLE
[webpack-config-terra] Replace node-sass with sass (dart-sass)

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-toolkit#676]
# Feature Request

## Description

As of October 2020 [node-sass]9https://www.npmjs.com/package/node-sass) is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated). The [sass](https://www.npmjs.com/package/sass) npm package is the replacement. 

While the upgrade to this package is incredibly easy ([see this branch](https://github.com/cerner/terra-toolkit/compare/main...switch-to-dart-sass)), this change has a ripple effect on screenshot comparisons downstream.

Specifically the sass package calculates a greater precision than the node-sass package.

For example, the sass package has a precision of 10 which is [non adjustable](https://github.com/sass/dart-sass#javascript-api). See [line-height](https://github.com/cerner/terra-core/blob/main/packages/terra-base/src/Base.scss#L26) in terra-base.
```css
body {
    color: #1c1f21;
    color: var(--terra-base-color, #1c1f21);
    font-size: 1rem;
    height: 100%;
    height: var(--terra-base-body-height, 100%);
    line-height: 1.4285714286;
    line-height: var(--terra-base-line-height, 1.4285714286)
}
```
Where as the node-sass package has a default precision of [5](https://github.com/sass/node-sass#precision)
```css
body {
    color: #1c1f21;
    color: var(--terra-base-color, #1c1f21);
    font-size: 1rem;
    height: 100%;
    height: var(--terra-base-body-height, 100%);
    line-height: 1.42857;
    line-height: var(--terra-base-line-height, 1.42857)
}
```
The effect in this specific instance on wdio tests is that content down the page increasingly gets 'off' according to the screenshot comparison:
![open_fullscreen_modal](https://user-images.githubusercontent.com/1588747/122993113-88347500-d36c-11eb-8a10-037cc9e08d1c.png)

## Options

1. Consider this passive and require consuming teams and ourselves to update screenshots.
2. Consider this passive, hunt down any css variable with greater than 5 precision and update it prior to release.
3. Consider this non passive and include it in the next mvb, or release an mvb.
